export interface TiptapNode {
  type?: string;
  text?: string;
  attrs?: { level?: number; language?: string };
  marks?: Array<{ type?: string; attrs?: { href?: string } }>;
  content?: TiptapNode[];
}

const GENERATED_MARKER = '<!-- Generated by AgentFlow. Manual changes may be overwritten. -->';

export function markdownToTiptapHtml(markdown: string): string {
  const lines = markdown.split(/\r?\n/);
  const blocks: string[] = [];
  let index = 0;

  while (index < lines.length) {
    const line = lines[index];
    if (!line.trim()) {
      index += 1;
      continue;
    }

    if (index === 0 && line === '---') {
      const block = collectUntil(lines, index, /^---$/);
      blocks.push(`<pre><code>${escapeHtml(block.content.join('\n'))}</code></pre>`);
      index = block.nextIndex;
      continue;
    }

    const fence = line.match(/^```([A-Za-z0-9_-]+)?$/);
    if (fence) {
      const block = collectUntil(lines, index, /^```$/);
      const language = fence[1] ? ` data-language="${escapeHtml(fence[1])}"` : '';
      blocks.push(`<pre><code${language}>${escapeHtml(block.content.slice(1, -1).join('\n'))}</code></pre>`);
      index = block.nextIndex;
      continue;
    }

    const heading = line.match(/^(#{1,3})\s+(.+)$/);
    if (heading) {
      blocks.push(`<h${heading[1].length}>${inlineMarkdownToHtml(heading[2])}</h${heading[1].length}>`);
      index += 1;
      continue;
    }

    if (/^-\s+/.test(line)) {
      const items: string[] = [];
      while (index < lines.length && /^-\s+/.test(lines[index])) {
        items.push(`<li>${inlineMarkdownToHtml(lines[index].replace(/^-\s+/, ''))}</li>`);
        index += 1;
      }
      blocks.push(`<ul>${items.join('')}</ul>`);
      continue;
    }

    const paragraph: string[] = [];
    while (index < lines.length && lines[index].trim() && !/^(#{1,3})\s+/.test(lines[index]) && !/^-\s+/.test(lines[index])) {
      paragraph.push(lines[index]);
      index += 1;
    }
    blocks.push(`<p>${inlineMarkdownToHtml(paragraph.join(' '))}</p>`);
  }

  return blocks.join('');
}

export function splitMarkdownFrontmatter(markdown: string): { frontmatter?: string; body: string } {
  const content = stripGeneratedMarker(markdown);
  const match = content.match(/^(---\r?\n[\s\S]*?\r?\n---)(?:\r?\n)?([\s\S]*)$/);
  if (!match) return { body: content };
  return { frontmatter: match[1], body: (match[2] ?? '').replace(/^(?:\r?\n)+/, '') };
}

export function combineMarkdownFrontmatter(frontmatter: string | undefined, body: string): string {
  if (!frontmatter?.trim()) return body;
  return body.trim() ? `${frontmatter.trimEnd()}\n\n${body.trimStart()}` : `${frontmatter.trimEnd()}\n`;
}

export function tiptapJsonToMarkdown(document: TiptapNode): string {
  return (document.content ?? [])
    .map(nodeToMarkdown)
    .filter(Boolean)
    .join('\n\n')
    .trim();
}

function nodeToMarkdown(node: TiptapNode): string {
  if (node.type === 'heading') return `${'#'.repeat(clampHeadingLevel(node.attrs?.level))} ${childrenToMarkdown(node)}`;
  if (node.type === 'paragraph') return childrenToMarkdown(node);
  if (node.type === 'codeBlock') return codeBlockToMarkdown(node);
  if (node.type === 'bulletList') return (node.content ?? []).map((item) => `- ${childrenToMarkdown(item)}`).join('\n');
  if (node.type === 'listItem') return childrenToMarkdown(node);
  if (node.type === 'hardBreak') return '\n';
  if (node.type === 'text') return textToMarkdown(node);
  return childrenToMarkdown(node);
}

function childrenToMarkdown(node: TiptapNode): string {
  return (node.content ?? []).map(nodeToMarkdown).join('').trim();
}

function textToMarkdown(node: TiptapNode): string {
  return (node.marks ?? []).reduce((value, mark) => {
    if (mark.type === 'bold') return `**${value}**`;
    if (mark.type === 'code') return `\`${value}\``;
    if (mark.type === 'link' && mark.attrs?.href) return `[${value}](${mark.attrs.href})`;
    return value;
  }, node.text ?? '');
}

function codeBlockToMarkdown(node: TiptapNode): string {
  const content = childrenToMarkdown(node);
  if (content.startsWith('---\n') && content.endsWith('\n---')) return content;
  const language = node.attrs?.language ?? '';
  return `\`\`\`${language}\n${content}\n\`\`\``;
}

function inlineMarkdownToHtml(value: string): string {
  return escapeHtml(value)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g, '<a href="$2">$1</a>');
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function clampHeadingLevel(value: number | undefined): number {
  if (value === 1 || value === 2 || value === 3) return value;
  return 2;
}

function stripGeneratedMarker(markdown: string): string {
  let content = markdown.trimStart();
  if (content.startsWith(GENERATED_MARKER)) content = content.slice(GENERATED_MARKER.length).replace(/^(?:\r?\n)+/, '');
  if (content.trimEnd().endsWith(GENERATED_MARKER)) {
    content = content.trimEnd().slice(0, -GENERATED_MARKER.length).replace(/(?:\r?\n)+$/, '');
  }
  return content;
}

function collectUntil(lines: string[], startIndex: number, terminator: RegExp): { content: string[]; nextIndex: number } {
  const content = [lines[startIndex]];
  let index = startIndex + 1;
  while (index < lines.length) {
    content.push(lines[index]);
    index += 1;
    if (terminator.test(lines[index - 1])) break;
  }
  return { content, nextIndex: index };
}
