import { describe, expect, it } from 'vitest';
import { createDefaultPipeline } from '../src/pipeline/defaultPipeline';
import { parsePipelineJson, stringifyPipeline } from '../src/pipeline/parser';
import { generateAgentMarkdown, generateFiles, generateInstructionMarkdown, generatePromptMarkdown, generateSkillMarkdown } from '../src/pipeline/generators';
import { validatePipeline } from '../src/pipeline/validator';
import { calculateRiskScore } from '../src/pipeline/riskScore';
import { AgentPipeline, PromptNode } from '../src/pipeline/types';
import { normalizePipelineAgentReferences, resolveAgentReference, stripYamlQuotes } from '../src/pipeline/referenceResolver';
import { deriveVisibleFlowEdges } from '../src/webview/graph';
import { coerceFlowLayout, layoutFlowNodes } from '../src/webview/flowLayout';
import { estimateNodeTokenCount, estimateTokenCount, formatTokenBadge } from '../src/webview/tokenCounts';
import { renameNodeLabel } from '../src/webview/flowMutations';

describe('pipeline parsing', () => {
  it('round-trips the default pipeline schema', () => {
    const pipeline = createDefaultPipeline();
    const parsed = parsePipelineJson(stringifyPipeline(pipeline));
    expect(parsed.version).toBe(1);
    expect(parsed.nodes.length).toBeGreaterThan(10);
    expect(parsed.edges.length).toBeGreaterThan(10);
  });

  it('rejects duplicate node ids', () => {
    const pipeline = createDefaultPipeline();
    pipeline.nodes.push({ ...pipeline.nodes[0] });
    expect(() => parsePipelineJson(JSON.stringify(pipeline))).toThrow(/duplicate node id/);
  });
});

describe('default pipeline', () => {
  it('contains required preset agents', () => {
    const ids = createDefaultPipeline().nodes.map((node) => node.id);
    for (const id of ['router', 'context', 'planner', 'task-splitter', 'frontend', 'backend', 'frontend-review', 'backend-review', 'integration', 'test', 'fix', 'docs', 'final-review']) {
      expect(ids).toContain(id);
    }
  });
});

describe('markdown generators', () => {
  const pipeline = createDefaultPipeline();
  it('generates deterministic agent markdown with marker and artifacts', () => {
    const frontend = pipeline.nodes.find((node) => node.id === 'frontend' && node.type === 'agent');
    expect(frontend?.type).toBe('agent');
    const first = generateAgentMarkdown(frontend!);
    const second = generateAgentMarkdown(frontend!);
    expect(first).toBe(second);
    expect(first).toContain('<!-- Generated by Agent Flow');
    expect(first).toContain('Write `.agent-output/results/frontend-result.md`.');
  });

  it('keeps generated comments after frontmatter so VS Code highlights YAML correctly', () => {
    const frontend = pipeline.nodes.find((node) => node.id === 'frontend' && node.type === 'agent');
    const promptNode = pipeline.nodes.find((node): node is PromptNode => node.type === 'prompt');
    expect(frontend?.type).toBe('agent');
    expect(promptNode).toBeDefined();
    const agent = generateAgentMarkdown(frontend!);
    const prompt = generatePromptMarkdown(promptNode!);
    const instruction = generateInstructionMarkdown({ id: 'docs', type: 'instruction', label: 'Docs', applyTo: 'docs/**/*.md' });
    const skill = generateSkillMarkdown({ id: 'review-pr', type: 'skill', label: 'Review PR', description: 'Review changes.' });
    const artifact = generateFiles({ version: 1, name: 'Artifacts', nodes: [{ id: 'result', type: 'artifact', label: 'Result', path: '.agent-output/result.md' }], edges: [] }).find((file) => file.kind === 'artifact')?.content ?? '';

    for (const markdown of [agent, prompt, instruction, skill]) {
      expect(markdown.startsWith('---\n')).toBe(true);
      expect(markdown.trimEnd().endsWith('<!-- Generated by Agent Flow. Manual changes may be overwritten. -->')).toBe(true);
    }
    expect(artifact.startsWith('# Result\n')).toBe(true);
    expect(artifact.trimEnd().endsWith('<!-- Generated by Agent Flow. Manual changes may be overwritten. -->')).toBe(true);
  });

  it('does not duplicate generated comments when preserving edited markdown bodies', () => {
    const agent = generateAgentMarkdown({
      id: 'reviewer',
      type: 'agent',
      label: 'Reviewer',
      description: 'Reviews changes.',
      tools: ['read'],
      markdown: `---
name: "Reviewer"
tools:
  - "read"
---

# Custom Body

Keep this prose.

<!-- Generated by Agent Flow. Manual changes may be overwritten. -->`
    });

    expect(agent.match(/Generated by Agent Flow/g)).toHaveLength(1);
    expect(agent.startsWith('---\n')).toBe(true);
    expect(agent.trimEnd().endsWith('<!-- Generated by Agent Flow. Manual changes may be overwritten. -->')).toBe(true);
  });

  it('generates current custom agent frontmatter fields', () => {
    const agent = generateAgentMarkdown({
      id: 'reviewer',
      type: 'agent',
      label: 'Reviewer',
      description: 'Reviews changes.',
      tools: ['search'],
      calls: ['implementer'],
      argumentHint: '[pull request]',
      model: 'GPT-5.2 (copilot)',
      target: 'vscode',
      userInvocable: false,
      disableModelInvocation: true,
      handoffs: [{ label: 'Start Implementation', agent: 'implementer', prompt: 'Implement the review findings.', send: false }]
    });
    expect(agent).toContain('name: "Reviewer"');
    expect(agent).toContain('argument-hint: "[pull request]"');
    expect(agent).toContain('model: "GPT-5.2 (copilot)"');
    expect(agent).toContain('target: "vscode"');
    expect(agent).toContain('user-invocable: false');
    expect(agent).toContain('disable-model-invocation: true');
    expect(agent).toContain('agents:\n  - "implementer"');
    expect(agent).toContain('handoffs:\n  - label: "Start Implementation"\n    agent: "implementer"\n    prompt: "Implement the review findings."\n    send: false');
  });

  it('omits empty optional frontmatter fields', () => {
    const agent = generateAgentMarkdown({ id: 'agent', type: 'agent', label: 'Agent', description: '', tools: [], calls: [] });
    const prompt = generatePromptMarkdown({ id: 'prompt', type: 'prompt', label: 'Prompt', description: '', tools: [] });
    const instruction = generateInstructionMarkdown({ id: 'instruction', type: 'instruction', label: 'Instruction', description: '', applyTo: '', rules: [] });
    const skill = generateSkillMarkdown({ id: 'skill', type: 'skill', label: 'Skill', description: '', argumentHint: '', procedure: [] });

    for (const markdown of [agent, prompt, instruction, skill]) {
      expect(markdown).not.toContain('description:');
      expect(markdown).not.toContain('argument-hint:');
    }
    expect(instruction).not.toContain('applyTo:');
  });

  it('generates prompt markdown', () => {
    const prompt = pipeline.nodes.find((node) => node.type === 'prompt');
    expect(prompt?.type).toBe('prompt');
    expect(generatePromptMarkdown(prompt!)).toContain('Start with `router`.');
  });

  it('generates current prompt file frontmatter fields', () => {
    const prompt = generatePromptMarkdown({
      id: 'security-review',
      type: 'prompt',
      label: 'Security Review',
      description: 'Review a REST API.',
      startAgent: 'ask',
      argumentHint: '[endpoint]',
      model: 'Claude Sonnet 4',
      tools: ['search']
    });
    expect(prompt).toContain('name: "Security Review"');
    expect(prompt).toContain('argument-hint: "[endpoint]"');
    expect(prompt).toContain('agent: "ask"');
    expect(prompt).toContain('model: "Claude Sonnet 4"');
    expect(prompt).toContain('tools:\n  - "search"');
  });

  it('generates instruction markdown', () => {
    const instruction = generateInstructionMarkdown({ id: 'docs', type: 'instruction', label: 'Docs', description: 'Markdown standards.', applyTo: '**/*.md', excludeAgent: 'code-review', rules: ['Keep docs short.'] });
    expect(instruction).toContain('name: "Docs"');
    expect(instruction).toContain('description: "Markdown standards."');
    expect(instruction).toContain('applyTo: "**/*.md"');
    expect(instruction).toContain('excludeAgent: "code-review"');
  });

  it('generates skill markdown with activation criteria', () => {
    const skill = pipeline.nodes.find((node) => node.type === 'skill');
    expect(skill?.type).toBe('skill');
    expect(generateSkillMarkdown(skill!)).toContain('## Activation criteria');
  });

  it('does not generate flow JSON because Markdown files are the source of truth', () => {
    expect(generateFiles({ version: 1, name: 'Path', nodes: [], edges: [] }).some((file) => file.kind === 'pipeline' || file.path === '.github/agent-flow.json')).toBe(false);
  });

  it('generates current skill frontmatter fields', () => {
    const skill = generateSkillMarkdown({
      id: 'review-pr',
      type: 'skill',
      label: 'Review PR',
      description: 'Review a pull request.',
      argumentHint: '[pr-number]',
      userInvocable: false,
      disableModelInvocation: true,
      context: 'fork',
      procedure: ['Inspect diff.']
    });
    expect(skill).toContain('name: "review-pr"');
    expect(skill).toContain('description: "Review a pull request."');
    expect(skill).toContain('argument-hint: "[pr-number]"');
    expect(skill).toContain('user-invocable: false');
    expect(skill).toContain('disable-model-invocation: true');
    expect(skill).toContain('context: "fork"');
  });

  it('uses a node markdown override when edited from the webview', () => {
    const frontend = pipeline.nodes.find((node) => node.id === 'frontend' && node.type === 'agent');
    expect(frontend?.type).toBe('agent');
    expect(generateAgentMarkdown({ ...frontend!, markdown: '# Custom Agent\n\nEdited in Agent Flow.' })).toContain('<!-- Generated by Agent Flow');
    expect(generateAgentMarkdown({ ...frontend!, markdown: '# Custom Agent\n\nEdited in Agent Flow.' })).toContain('# Custom Agent');
  });

  it('updates generated frontmatter when config changes but preserves edited markdown body', () => {
    const agent = generateAgentMarkdown({
      id: 'reviewer',
      type: 'agent',
      label: 'Reviewer',
      description: 'Reviews changes.',
      tools: ['read', 'search'],
      calls: ['worker'],
      outputs: [],
      markdown: `---
name: "Old Reviewer"
tools:
  - "read"
---

# Custom Body

Keep this prose.`
    });

    expect(agent).toContain('name: "Reviewer"');
    expect(agent).toContain('tools:\n  - "read"\n  - "search"');
    expect(agent).toContain('agents:\n  - "worker"');
    expect(agent).toContain('# Custom Body');
    expect(agent).toContain('Keep this prose.');
    expect(agent).not.toContain('Old Reviewer');
  });

  it('generates actionable artifact and instruction references for agents', () => {
    const agent = generateAgentMarkdown({
      id: 'reviewer',
      type: 'agent',
      label: 'Reviewer',
      description: 'Reviews implementation.',
      tools: ['read'],
      inputs: ['.agent-output/implementation.md'],
      outputs: ['.agent-output/review.md'],
      artifactUsages: [
        { path: '.agent-output/implementation.md', action: 'read', instruction: 'Use this as the source of truth for the review.' },
        { path: '.agent-output/review.md', action: 'write', instruction: 'Write blocking findings first.' }
      ],
      instructionRefs: [
        { target: '.github/instructions/docs-scope.instructions.md', instruction: 'Apply when reviewing documentation changes.' }
      ]
    });

    expect(agent).toContain('# Artifact work');
    expect(agent).toContain('- Read `.agent-output/implementation.md`: Use this as the source of truth for the review.');
    expect(agent).toContain('- Write `.agent-output/review.md`: Write blocking findings first.');
    expect(agent).toContain('# Referenced instructions');
    expect(agent).toContain('- Follow `.github/instructions/docs-scope.instructions.md`: Apply when reviewing documentation changes.');
  });

  it('updates artifact work in edited agent markdown when config changes', () => {
    const agent = generateAgentMarkdown({
      id: 'writer',
      type: 'agent',
      label: 'Writer',
      tools: ['read'],
      outputs: ['.agent-output/summary.md'],
      artifactUsages: [
        { path: '.agent-output/summary.md', action: 'write', instruction: 'Create a summary with risks and next steps.' }
      ],
      markdown: `---
name: "Writer"
tools:
  - "read"
---

# Role

Keep this custom role text.

# Artifact work

None.

# Notes

Keep this custom note.`
    });

    expect(agent).toContain('# Role');
    expect(agent).toContain('Keep this custom role text.');
    expect(agent).toContain('# Artifact work');
    expect(agent).toContain('- Write `.agent-output/summary.md`: Create a summary with risks and next steps.');
    expect(agent).toContain('# Notes');
    expect(agent).toContain('Keep this custom note.');
    expect(agent).not.toContain('# Artifact work\n\nNone.');
  });

  it('generates actionable artifact and instruction references for prompts', () => {
    const prompt = generatePromptMarkdown({
      id: 'release-notes',
      type: 'prompt',
      label: 'Release Notes',
      description: 'Draft release notes.',
      requiredArtifacts: ['.agent-output/review.md'],
      artifactUsages: [
        { path: '.agent-output/review.md', action: 'read', instruction: 'Summarize only accepted findings.' }
      ],
      instructionRefs: [
        { target: '.github/instructions/docs-scope.instructions.md', instruction: 'Use the docs style rules.' }
      ]
    });

    expect(prompt).toContain('# Required artifacts');
    expect(prompt).toContain('- Read `.agent-output/review.md`: Summarize only accepted findings.');
    expect(prompt).toContain('# Referenced instructions');
    expect(prompt).toContain('- Follow `.github/instructions/docs-scope.instructions.md`: Use the docs style rules.');
  });

  it('honors explicit file paths for newly inserted Markdown-backed nodes', () => {
    const files = generateFiles({
      version: 1,
      name: 'Inserted nodes',
      nodes: [
        { id: 'new-agent-1', type: 'agent', label: 'New agent', agentFile: '.github/agents/new-agent-1.agent.md', tools: [], calls: [], outputs: [] },
        { id: 'new-prompt-1', type: 'prompt', label: 'New prompt', promptFile: '.github/prompts/new-prompt-1.prompt.md', tools: [] },
        { id: 'new-instruction-1', type: 'instruction', label: 'New instruction', instructionFile: '.github/instructions/new-instruction-1.instructions.md', applyTo: undefined },
        { id: 'new-skill-1', type: 'skill', label: 'New skill', skillFile: '.github/skills/new-skill-1/SKILL.md' },
        { id: 'new-artifact-1', type: 'artifact', label: 'New artifact', path: '.agent-output/new-artifact-1.md' },
        { id: 'new-gate-1', type: 'gate', label: 'New gate', condition: 'Define condition' },
        { id: 'new-handoff-1', type: 'handoff', label: 'New handoff' },
        { id: 'new-mcp-server-1', type: 'mcp-server', label: 'New MCP server' }
      ],
      edges: []
    }).map((file) => file.path);

    expect(files).toContain('.github/agents/new-agent-1.agent.md');
    expect(files).toContain('.github/prompts/new-prompt-1.prompt.md');
    expect(files).toContain('.github/instructions/new-instruction-1.instructions.md');
    expect(files).toContain('.github/skills/new-skill-1/SKILL.md');
    expect(files).toContain('.agent-output/new-artifact-1.md');
    expect(files).not.toContain('.github/gates/new-gate-1.md');
    expect(files).not.toContain('.github/handoffs/new-handoff-1.md');
    expect(files).not.toContain('.github/mcp-servers/new-mcp-server-1.md');
  });

  it('uses a renamed new node label for generated markdown file names', () => {
    const files = generateFiles({
      version: 1,
      name: 'New nodes',
      nodes: [
        renameNodeLabel({ id: 'new-agent-1', type: 'agent', label: 'New agent', agentFile: '.github/agents/new-agent-1.agent.md', tools: [], calls: [], outputs: [] }, 'Security Reviewer'),
        renameNodeLabel({ id: 'new-prompt-1', type: 'prompt', label: 'New prompt', promptFile: '.github/prompts/new-prompt-1.prompt.md', tools: [] }, 'Release Notes'),
        renameNodeLabel({ id: 'new-instruction-1', type: 'instruction', label: 'New instruction', instructionFile: '.github/instructions/new-instruction-1.instructions.md', applyTo: '**/*.md' }, 'Docs Scope'),
        renameNodeLabel({ id: 'new-skill-1', type: 'skill', label: 'New skill', skillFile: '.github/skills/new-skill-1/SKILL.md' }, 'Review PR')
      ],
      edges: []
    }).map((file) => file.path);

    expect(files).toContain('.github/agents/security-reviewer.agent.md');
    expect(files).toContain('.github/prompts/release-notes.prompt.md');
    expect(files).toContain('.github/instructions/docs-scope.instructions.md');
    expect(files).toContain('.github/skills/review-pr/SKILL.md');
  });

  it('uses renamed new node labels in generated markdown content', () => {
    const files = generateFiles({
      version: 1,
      name: 'New node content',
      nodes: [
        renameNodeLabel({ id: 'new-agent-1', type: 'agent', label: 'New agent', agentFile: '.github/agents/new-agent-1.agent.md', tools: [], calls: [], outputs: [] }, 'Security Reviewer'),
        renameNodeLabel({ id: 'new-prompt-1', type: 'prompt', label: 'New prompt', promptFile: '.github/prompts/new-prompt-1.prompt.md', tools: [] }, 'Release Notes'),
        renameNodeLabel({ id: 'new-instruction-1', type: 'instruction', label: 'New instruction', instructionFile: '.github/instructions/new-instruction-1.instructions.md', applyTo: '**/*.md' }, 'Docs Scope'),
        renameNodeLabel({ id: 'new-skill-1', type: 'skill', label: 'New skill', skillFile: '.github/skills/new-skill-1/SKILL.md' }, 'Review PR')
      ],
      edges: []
    });

    expect(files.find((file) => file.path === '.github/agents/security-reviewer.agent.md')?.content).toContain('name: "Security Reviewer"');
    expect(files.find((file) => file.path === '.github/prompts/release-notes.prompt.md')?.content).toContain('# Release Notes');
    expect(files.find((file) => file.path === '.github/instructions/docs-scope.instructions.md')?.content).toContain('# Docs Scope');
    expect(files.find((file) => file.path === '.github/skills/review-pr/SKILL.md')?.content).toContain('name: "review-pr"');
    expect(files.find((file) => file.path === '.github/skills/review-pr/SKILL.md')?.content).toContain('# Review PR');
  });

  it('generates all files in deterministic path order', () => {
    const files = generateFiles(pipeline);
    expect(files.map((file) => file.path)).toEqual([...files.map((file) => file.path)].sort());
    expect(files.some((file) => file.path === 'AGENT_PIPELINE.md')).toBe(false);
  });
});

describe('webview graph projection', () => {
  it('coerces and applies flow layout settings', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Layouts',
      nodes: [
        { id: 'prompt', type: 'prompt', label: 'Prompt', startAgent: 'agent', position: { x: 11, y: 22 } },
        { id: 'agent', type: 'agent', label: 'Agent', calls: ['skill'], outputs: [] },
        { id: 'skill', type: 'skill', label: 'Skill' }
      ],
      edges: []
    };

    expect(coerceFlowLayout('vertical')).toBe('vertical');
    expect(coerceFlowLayout('compact')).toBe('compact');
    expect(coerceFlowLayout('manual')).toBe('compact');
    expect(coerceFlowLayout('unknown')).toBe('compact');
    expect(layoutFlowNodes(pipeline, 'vertical').get('agent')?.y).toBeGreaterThan(layoutFlowNodes(pipeline, 'vertical').get('prompt')?.y ?? 0);
    expect(layoutFlowNodes(pipeline, 'horizontal').get('agent')?.x).toBeGreaterThan(layoutFlowNodes(pipeline, 'horizontal').get('prompt')?.x ?? 0);
    expect(layoutFlowNodes(pipeline, 'typeColumns').get('agent')?.x).toBeGreaterThan(layoutFlowNodes(pipeline, 'typeColumns').get('prompt')?.x ?? 0);
    expect(layoutFlowNodes(pipeline, 'compact').size).toBe(3);
  });

  it('places large compact layouts without node collisions', () => {
    const nodes: AgentPipeline['nodes'] = Array.from({ length: 30 }, (_, index) => ({
      id: `node-${index}`,
      type: index % 3 === 0 ? 'agent' : index % 3 === 1 ? 'prompt' : 'instruction',
      label: `Node ${index}`
    } as AgentPipeline['nodes'][number]));
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Large layout',
      nodes,
      edges: nodes.slice(1).map((node, index) => ({ id: `edge-${index}`, from: nodes[index].id, to: node.id, kind: 'flow' }))
    };

    const positions = [...layoutFlowNodes(pipeline, 'compact').values()];
    const occupied = new Set(positions.map((position) => `${position.x}:${position.y}`));

    expect(positions).toHaveLength(nodes.length);
    expect(occupied.size).toBe(nodes.length);
    expect(Math.max(...positions.map((position) => position.x))).toBeLessThan(245 * 8);
  });

  it('estimates token badges for generated node content', () => {
    const pipeline = createDefaultPipeline();
    const frontend = pipeline.nodes.find((node) => node.id === 'frontend');
    expect(frontend).toBeDefined();
    expect(estimateTokenCount('')).toBe(0);
    expect(estimateTokenCount('123456789')).toBe(3);
    expect(estimateNodeTokenCount(pipeline, frontend!)).toBeGreaterThan(50);
    expect(formatTokenBadge(999)).toBe('~999 tok');
    expect(formatTokenBadge(1200)).toBe('~1.2k tok');
  });

  it('projects live configuration references into visible flow edges', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Live refs',
      nodes: [
        { id: 'prompt', type: 'prompt', label: 'Prompt', startAgent: 'Router' },
        { id: 'router', type: 'agent', label: 'Router', calls: ['"Worker Agent"'], outputs: ['.agent-output/work.md'] },
        { id: 'worker-agent', type: 'agent', label: 'Worker Agent', inputs: ['.agent-output/work.md'] },
        { id: 'work-artifact', type: 'artifact', label: 'Work artifact', path: '.agent-output/work.md' }
      ],
      edges: []
    };

    expect(deriveVisibleFlowEdges(pipeline).map((edge) => [edge.id, edge.source, edge.target, edge.data?.derivedFrom])).toEqual([
      ['ref:prompt:prompt:startAgent:router', 'prompt', 'router', 'prompt.startAgent'],
      ['ref:agent:router:calls:worker-agent', 'router', 'worker-agent', 'agent.calls'],
      ['ref:artifact-output:router:work-artifact', 'router', 'work-artifact', 'agent.outputs'],
      ['ref:artifact-input:work-artifact:worker-agent', 'work-artifact', 'worker-agent', 'agent.inputs']
    ]);
  });

  it('projects handoffs as distinct visible edges', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Handoffs',
      nodes: [
        { id: 'router', type: 'agent', label: 'Router', calls: [], outputs: [], handoffs: [{ label: 'Escalate', agent: 'worker', prompt: 'Take over.' }] },
        { id: 'worker', type: 'agent', label: 'Worker', outputs: [] }
      ],
      edges: []
    };

    expect(deriveVisibleFlowEdges(pipeline).map((edge) => [edge.source, edge.target, edge.label, edge.data.kind, edge.data.derivedFrom, edge.style?.strokeDasharray])).toEqual([
      ['router', 'worker', 'Escalate', 'handoff', 'agent.handoffs', '3 3']
    ]);
  });

  it('projects prompt artifact usage and instruction references into visible edges', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Reference edges',
      nodes: [
        { id: 'prompt', type: 'prompt', label: 'Prompt', artifactUsages: [{ path: '.agent-output/brief.md', action: 'read', instruction: 'Summarize it.' }], instructionRefs: [{ target: '.github/instructions/docs.instructions.md', instruction: 'Use docs rules.' }] },
        { id: 'artifact', type: 'artifact', label: 'Brief', path: '.agent-output/brief.md' },
        { id: 'docs', type: 'instruction', label: 'Docs', instructionFile: '.github/instructions/docs.instructions.md', applyTo: 'docs/**/*.md' }
      ],
      edges: []
    };

    expect(deriveVisibleFlowEdges(pipeline).map((edge) => [edge.source, edge.target, edge.label, edge.data.derivedFrom, edge.data.kind])).toEqual([
      ['artifact', 'prompt', 'reads', 'prompt.artifactUsages', 'reference'],
      ['docs', 'prompt', 'instructs', 'prompt.instructionRefs', 'reference']
    ]);
  });


  it('projects instruction file references into visible edges', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Instruction refs',
      nodes: [
        { id: 'atom', type: 'instruction', label: 'Atom', instructionFile: '.github/instructions/atom.instructions.md', applyTo: '!**/*', instructionRefs: [{ target: '.github/instructions/template.instructions.md' }] },
        { id: 'template', type: 'instruction', label: 'Template', instructionFile: '.github/instructions/template.instructions.md', applyTo: '**/*' }
      ],
      edges: []
    };

    expect(deriveVisibleFlowEdges(pipeline).map((edge) => [edge.source, edge.target, edge.label, edge.data.derivedFrom, edge.data.kind])).toEqual([
      ['template', 'atom', 'instructs', 'instruction.instructionRefs', 'reference']
    ]);
  });

  it('keeps explicit user-drawn edges editable and avoids duplicate reference previews', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Explicit refs',
      nodes: [
        { id: 'router', type: 'agent', label: 'Router', calls: ['worker'], outputs: [] },
        { id: 'worker', type: 'agent', label: 'Worker', outputs: [] }
      ],
      edges: [{ id: 'router-to-worker', from: 'router', to: 'worker', kind: 'flow', label: 'handoff' }]
    };

    expect(deriveVisibleFlowEdges(pipeline).map((edge) => [edge.id, edge.source, edge.target, edge.data?.derivedFrom])).toEqual([
      ['router-to-worker', 'router', 'worker', 'pipeline.edges']
    ]);
  });

  it('keeps generic stored flow edges visible even without a live reference', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Manual flow',
      nodes: [
        { id: 'router', type: 'agent', label: 'Router', calls: [], outputs: [] },
        { id: 'worker', type: 'agent', label: 'Worker', outputs: [] }
      ],
      edges: [{ id: 'manual-flow', from: 'router', to: 'worker', kind: 'flow' }]
    };

    expect(deriveVisibleFlowEdges(pipeline).map((edge) => [edge.id, edge.source, edge.target, edge.label])).toEqual([
      ['manual-flow', 'router', 'worker', undefined]
    ]);
  });

  it('does not render generic flow labels and keeps meaningful edge labels', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Edge labels',
      nodes: [
        { id: 'router', type: 'agent', label: 'Router', calls: ['worker'], outputs: ['.agent-output/result.md'] },
        { id: 'worker', type: 'agent', label: 'Worker', outputs: [] },
        { id: 'artifact', type: 'artifact', label: 'Result', path: '.agent-output/result.md' },
        { id: 'gate', type: 'gate', label: 'Ready?', condition: 'Tests passed' }
      ],
      edges: [
        { id: 'router-to-worker', from: 'router', to: 'worker', kind: 'flow' },
        { id: 'router-to-artifact', from: 'router', to: 'artifact', kind: 'artifact', artifact: '.agent-output/result.md' },
        { id: 'worker-to-gate', from: 'worker', to: 'gate', kind: 'gate', label: 'true' },
        { id: 'gate-to-router', from: 'gate', to: 'router', kind: 'flow', label: 'retry' }
      ]
    };

    expect(deriveVisibleFlowEdges(pipeline).map((edge) => [edge.id, edge.label])).toEqual([
      ['router-to-worker', undefined],
      ['router-to-artifact', '.agent-output/result.md'],
      ['worker-to-gate', 'true'],
      ['gate-to-router', 'retry']
    ]);
  });

  it('hides stored handoff edges when the handoff reference is removed', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Unchecked refs',
      nodes: [
        { id: 'router', type: 'agent', label: 'Router', calls: [], outputs: [] },
        { id: 'worker', type: 'agent', label: 'Worker', outputs: [] }
      ],
      edges: [{ id: 'router-to-worker', from: 'router', to: 'worker', kind: 'handoff' }]
    };

    expect(deriveVisibleFlowEdges(pipeline)).toEqual([]);
  });

  it('hides stored prompt edges when the start agent reference is removed', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Prompt refs',
      nodes: [
        { id: 'prompt', type: 'prompt', label: 'Prompt' },
        { id: 'router', type: 'agent', label: 'Router', outputs: [] }
      ],
      edges: [{ id: 'prompt-to-router', from: 'prompt', to: 'router', kind: 'prompt' }]
    };

    expect(deriveVisibleFlowEdges(pipeline)).toEqual([]);
  });

  it('hides stored artifact-node edges when input or output references are removed', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Artifact refs',
      nodes: [
        { id: 'producer', type: 'agent', label: 'Producer', outputs: [] },
        { id: 'artifact', type: 'artifact', label: 'Artifact', path: '.agent-output/result.md' },
        { id: 'consumer', type: 'agent', label: 'Consumer', inputs: [], outputs: [] }
      ],
      edges: [
        { id: 'producer-to-artifact', from: 'producer', to: 'artifact', kind: 'artifact', artifact: '.agent-output/result.md' },
        { id: 'artifact-to-consumer', from: 'artifact', to: 'consumer', kind: 'artifact', artifact: '.agent-output/result.md' }
      ]
    };

    expect(deriveVisibleFlowEdges(pipeline)).toEqual([]);
  });
});

describe('agent reference normalization', () => {
  it('strips YAML quotes and resolves display-name references to agent ids', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Quoted calls',
      nodes: [
        { id: 'alice-jira-ticket-formatter', type: 'agent', label: 'Alice (Jira Ticket Formatter)', calls: ['"Riker (Project Manager)"'] },
        { id: 'riker-project-manager', type: 'agent', label: 'Riker (Project Manager)' }
      ],
      edges: [{ id: 'alice-to-riker', from: 'alice-jira-ticket-formatter', to: '"Riker (Project Manager)"', kind: 'flow' }]
    };
    expect(stripYamlQuotes('"Riker (Project Manager)"')).toBe('Riker (Project Manager)');
    expect(resolveAgentReference('"Riker (Project Manager)"', pipeline.nodes)).toBe('riker-project-manager');
    const normalized = normalizePipelineAgentReferences(pipeline);
    expect(normalized.nodes[0].type === 'agent' && normalized.nodes[0].calls).toEqual(['riker-project-manager']);
    expect(normalized.edges[0].to).toBe('riker-project-manager');
  });
});

describe('validation rules', () => {
  it('does not report quoted display-name subagent references as unknown', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Quoted calls',
      nodes: [
        { id: 'alice-jira-ticket-formatter', type: 'agent', label: 'Alice (Jira Ticket Formatter)', calls: ['"Riker (Project Manager)"'], outputs: ['.agent-output/alice.md'] },
        { id: 'riker-project-manager', type: 'agent', label: 'Riker (Project Manager)', outputs: ['.agent-output/riker.md'] }
      ],
      edges: [{ id: 'alice-to-riker', from: 'alice-jira-ticket-formatter', to: '"Riker (Project Manager)"', kind: 'flow' }]
    };
    const ids = validatePipeline(pipeline).map((finding) => finding.ruleId);
    expect(ids).not.toContain('unknown-subagent');
    expect(ids).not.toContain('unknown-edge-to');
  });

  it('detects unknown subagents, unknown prompt agents, broad applyTo, and risky tools', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Risky',
      nodes: [
        { id: 'a', type: 'agent', label: 'A', tools: ['edit', 'execute'], calls: ['missing'], outputs: [] },
        { id: 'p', type: 'prompt', label: 'P', startAgent: 'missing-agent' },
        { id: 'i', type: 'instruction', label: 'I', applyTo: '**/*' },
        { id: 's', type: 'skill', label: 'S', description: 'general' }
      ],
      edges: []
    };
    const ids = validatePipeline(pipeline).map((finding) => finding.ruleId);
    expect(ids).toContain('unknown-subagent');
    expect(ids).toContain('prompt-unknown-agent');
    expect(ids).toContain('broad-apply-to');
    expect(ids).toContain('broad-agent-tools');
    expect(ids).toContain('missing-command-safety');
    expect(ids).toContain('generic-skill-description');
  });

  it('allows bounded default test/fix cycle via gate max iterations', () => {
    const ids = validatePipeline(createDefaultPipeline()).map((finding) => finding.ruleId);
    expect(ids).not.toContain('unbounded-cycle');
  });
});

describe('risk score', () => {
  it('scores context risk reasons', () => {
    const risk = calculateRiskScore(createDefaultPipeline(), { copilotInstructionsLines: 280 });
    expect(risk.score).toBeGreaterThan(0);
    expect(risk.reasons.join('\n')).toContain('copilot-instructions.md has 280 lines');
  });
});
