import { describe, expect, it } from 'vitest';
import { createDefaultPipeline } from '../src/pipeline/defaultPipeline';
import { parsePipelineJson, stringifyPipeline } from '../src/pipeline/parser';
import { generateAgentMarkdown, generateFiles, generateInstructionMarkdown, generateMermaid, generatePromptMarkdown, generateSkillMarkdown } from '../src/pipeline/generators';
import { validatePipeline } from '../src/pipeline/validator';
import { calculateRiskScore } from '../src/pipeline/riskScore';
import { AgentPipeline } from '../src/pipeline/types';

describe('pipeline parsing', () => {
  it('round-trips the default pipeline schema', () => {
    const pipeline = createDefaultPipeline();
    const parsed = parsePipelineJson(stringifyPipeline(pipeline));
    expect(parsed.version).toBe(1);
    expect(parsed.nodes.length).toBeGreaterThan(10);
    expect(parsed.edges.length).toBeGreaterThan(10);
  });

  it('rejects duplicate node ids', () => {
    const pipeline = createDefaultPipeline();
    pipeline.nodes.push({ ...pipeline.nodes[0] });
    expect(() => parsePipelineJson(JSON.stringify(pipeline))).toThrow(/duplicate node id/);
  });
});

describe('default pipeline', () => {
  it('contains required preset agents', () => {
    const ids = createDefaultPipeline().nodes.map((node) => node.id);
    for (const id of ['router', 'context', 'planner', 'task-splitter', 'frontend', 'backend', 'frontend-review', 'backend-review', 'integration', 'test', 'fix', 'docs', 'final-review']) {
      expect(ids).toContain(id);
    }
  });
});

describe('markdown generators', () => {
  const pipeline = createDefaultPipeline();
  it('generates deterministic agent markdown with marker and artifacts', () => {
    const frontend = pipeline.nodes.find((node) => node.id === 'frontend' && node.type === 'agent');
    expect(frontend?.type).toBe('agent');
    const first = generateAgentMarkdown(frontend!);
    const second = generateAgentMarkdown(frontend!);
    expect(first).toBe(second);
    expect(first).toContain('<!-- Generated by AgentFlow');
    expect(first).toContain('Write `.agent-output/results/frontend-result.md`.');
  });

  it('generates prompt markdown', () => {
    const prompt = pipeline.nodes.find((node) => node.type === 'prompt');
    expect(prompt?.type).toBe('prompt');
    expect(generatePromptMarkdown(prompt!)).toContain('Start with `router`.');
  });

  it('generates instruction markdown', () => {
    expect(generateInstructionMarkdown({ id: 'docs', type: 'instruction', label: 'Docs', applyTo: '**/*.md', rules: ['Keep docs short.'] })).toContain('applyTo: "**/*.md"');
  });

  it('generates skill markdown with activation criteria', () => {
    const skill = pipeline.nodes.find((node) => node.type === 'skill');
    expect(skill?.type).toBe('skill');
    expect(generateSkillMarkdown(skill!)).toContain('## Activation criteria');
  });

  it('generates all files in deterministic path order', () => {
    const files = generateFiles(pipeline);
    expect(files.map((file) => file.path)).toEqual([...files.map((file) => file.path)].sort());
    expect(files.some((file) => file.path === 'AGENT_PIPELINE.md')).toBe(true);
  });
});

describe('mermaid generator', () => {
  it('exports a flowchart with edges', () => {
    const mermaid = generateMermaid(createDefaultPipeline());
    expect(mermaid).toContain('flowchart TD');
    expect(mermaid).toContain('router --> context');
    expect(mermaid).toContain('tests-green{Tests Green?}');
  });
});

describe('validation rules', () => {
  it('detects unknown subagents, unknown prompt agents, broad applyTo, and risky tools', () => {
    const pipeline: AgentPipeline = {
      version: 1,
      name: 'Risky',
      nodes: [
        { id: 'a', type: 'agent', label: 'A', tools: ['editFiles', 'runCommands'], calls: ['missing'], outputs: [] },
        { id: 'p', type: 'prompt', label: 'P', startAgent: 'missing-agent' },
        { id: 'i', type: 'instruction', label: 'I', applyTo: '**/*' },
        { id: 's', type: 'skill', label: 'S', description: 'general' }
      ],
      edges: []
    };
    const ids = validatePipeline(pipeline).map((finding) => finding.ruleId);
    expect(ids).toContain('unknown-subagent');
    expect(ids).toContain('prompt-unknown-agent');
    expect(ids).toContain('broad-apply-to');
    expect(ids).toContain('broad-agent-tools');
    expect(ids).toContain('missing-command-safety');
    expect(ids).toContain('generic-skill-description');
  });

  it('allows bounded default test/fix cycle via gate max iterations', () => {
    const ids = validatePipeline(createDefaultPipeline()).map((finding) => finding.ruleId);
    expect(ids).not.toContain('unbounded-cycle');
  });
});

describe('risk score', () => {
  it('scores context risk reasons', () => {
    const risk = calculateRiskScore(createDefaultPipeline(), { copilotInstructionsLines: 280 });
    expect(risk.score).toBeGreaterThan(0);
    expect(risk.reasons.join('\n')).toContain('copilot-instructions.md has 280 lines');
  });
});
