import { AgentNode } from '../types';
import { normalizeToolsForVsCode } from '../toolNormalization';
import { GENERATED_MARKER, ensureTrailingNewline, list, yamlBooleanLine, yamlList, yamlString, yamlStringLine } from './shared';

export function agentFilePath(node: AgentNode): string {
  return node.agentFile ?? `.github/agents/${node.id}.agent.md`;
}

export function generateAgentMarkdown(node: AgentNode): string {
  if (node.markdown?.trim()) return ensureTrailingNewline(node.markdown.includes('Generated by AgentFlow') ? node.markdown : `${GENERATED_MARKER}\n${node.markdown}`);

  const content = `${GENERATED_MARKER}
---
name: ${yamlString(node.label)}
description: ${yamlString(node.description ?? node.label)}
${yamlStringLine('argument-hint', node.argumentHint)}${yamlStringLine('model', node.model)}${yamlStringLine('target', node.target)}${yamlBooleanLine('user-invocable', node.userInvocable)}${yamlBooleanLine('disable-model-invocation', node.disableModelInvocation)}${yamlAgentHandoffs(node.handoffs)}
${yamlList('tools', normalizeToolsForVsCode(node.tools))}
${yamlList('agents', node.calls)}
---

# Role

${node.description ?? `You are responsible for ${node.label}.`}

# Required input

${list((node.inputs ?? []).map((input) => `Read \`${input}\` first.`))}

# Context budget

${list(node.contextBudget)}

# Scope rules

${list(node.rules)}

# Edit rules

${list(node.editRules)}

# Allowed skills

${list(node.allowedSkills)}

# Forbidden changes

${list(node.forbiddenChanges)}

# Command safety

${list(node.commandSafety, (node.tools?.includes('execute') || node.tools?.includes('runCommands')) ? '- Prefer the smallest relevant command and avoid destructive commands.' : 'No command execution expected.')}

# Verification

${list(node.verificationRules)}

# Output

${list((node.outputs ?? []).map((output) => `Write \`${output}\`.`))}
`;
  return ensureTrailingNewline(content);
}

function yamlAgentHandoffs(handoffs: AgentNode['handoffs']): string {
  if (!handoffs || handoffs.length === 0) return '';
  return `handoffs:\n${handoffs.map((handoff) => {
    const lines = [`  - label: ${yamlString(handoff.label)}`, `    agent: ${yamlString(handoff.agent)}`];
    if (handoff.prompt) lines.push(`    prompt: ${yamlString(handoff.prompt)}`);
    if (typeof handoff.send === 'boolean') lines.push(`    send: ${handoff.send}`);
    if (handoff.model) lines.push(`    model: ${yamlString(handoff.model)}`);
    return lines.join('\n');
  }).join('\n')}\n`;
}
