import { InstructionNode } from '../types';
import { GENERATED_MARKER, ensureTrailingNewline, frontmatterValue, list } from './shared';

export function instructionFilePath(node: InstructionNode): string {
  return node.instructionFile ?? `.github/instructions/${node.id}.instructions.md`;
}

export function generateInstructionMarkdown(node: InstructionNode): string {
  if (node.markdown?.trim()) return ensureTrailingNewline(node.markdown.includes('Generated by AgentFlow') ? node.markdown : `${GENERATED_MARKER}\n${node.markdown}`);

  return ensureTrailingNewline(`${GENERATED_MARKER}
---
applyTo: "${frontmatterValue(node.applyTo)}"
description: "${frontmatterValue(node.description ?? node.label)}"
---

# ${node.label}

${node.description ?? ''}

# Rules

${list(node.rules)}
`);
}
