import { InstructionNode } from '../types';
import { GENERATED_MARKER, ensureTrailingNewline, list, yamlString, yamlStringLine } from './shared';

export function instructionFilePath(node: InstructionNode): string {
  return node.instructionFile ?? `.github/instructions/${node.id}.instructions.md`;
}

export function generateInstructionMarkdown(node: InstructionNode): string {
  if (node.markdown?.trim()) return ensureTrailingNewline(node.markdown.includes('Generated by AgentFlow') ? node.markdown : `${GENERATED_MARKER}\n${node.markdown}`);

  return ensureTrailingNewline(`${GENERATED_MARKER}
---
name: ${yamlString(node.label)}
description: ${yamlString(node.description ?? node.label)}
applyTo: ${yamlString(node.applyTo)}
${yamlStringLine('excludeAgent', node.excludeAgent)}
---

# ${node.label}

${node.description ?? ''}

# Rules

${list(node.rules)}
`);
}
