import { PromptNode } from '../types';
import { GENERATED_MARKER, ensureTrailingNewline, list, yamlList, yamlString, yamlStringLine } from './shared';

export function promptFilePath(node: PromptNode): string {
  return node.promptFile ?? `.github/prompts/${node.id}.prompt.md`;
}

export function generatePromptMarkdown(node: PromptNode): string {
  if (node.markdown?.trim()) return ensureTrailingNewline(node.markdown.includes('Generated by AgentFlow') ? node.markdown : `${GENERATED_MARKER}\n${node.markdown}`);

  return ensureTrailingNewline(`${GENERATED_MARKER}
---
name: ${yamlString(node.label)}
description: ${yamlString(node.description ?? node.label)}
${yamlStringLine('argument-hint', node.argumentHint)}${yamlStringLine('agent', node.startAgent)}${yamlStringLine('model', node.model)}
${yamlList('tools', node.tools)}
---

# ${node.label}

${node.description ?? ''}

# Start agent

${node.startAgent ? `Start with \`${node.startAgent}\`.` : 'No start agent configured.'}

# Workflow

${list(node.workflow)}

# Constraints and non-goals

${list(node.constraints)}

# Required artifacts

${list(node.requiredArtifacts)}

# Definition of done

${list(node.definitionOfDone)}
`);
}
