import { ArtifactUsage, ReferenceInstruction, ReferenceRole } from '../types';
import { normalizeToolsForVsCode } from '../toolNormalization';

export const GENERATED_MARKER = '<!-- Generated by Agent Flow. Manual changes may be overwritten. -->';
export const AGENT_FLOW_ACTIVITY_REPORT_TOOL = 'agentflow_report_activity';
export const AGENT_FLOW_ACTIVITY_REPORTING_HEADING = 'Agent Flow activity reporting';
const LEGACY_GENERATED_MARKER = '<!-- Generated by AgentFlow. Manual changes may be overwritten. -->';

const activityReportingRules = [
  `Use \`${AGENT_FLOW_ACTIVITY_REPORT_TOOL}\` for short, sanitized workspace-local updates when work starts, notable tool/file/artifact/handoff activity happens, work completes, or work fails.`,
  'Report only the node id or file, phase, short summary, and optional tool or artifact path.',
  'Do not include raw prompts, secrets, credentials, tokens, or full file contents.'
];

export function list(items: string[] | undefined, fallback = 'None.'): string {
  if (!items || items.length === 0) return fallback;
  return items.map((item) => `- ${item}`).join('\n');
}

export function artifactUsageList(usages: ArtifactUsage[] | undefined, fallbackPaths?: string[], fallback = 'None.'): string {
  if (usages?.length) {
    return usages.map((usage) => referenceBlock('artifact-ref', { action: usage.action, path: usage.path }, usage.instruction, '$artifact', usage.path)).join('\n\n');
  }
  return list(fallbackPaths, fallback);
}

export function referenceInstructionList(refs: ReferenceInstruction[] | undefined, fallback = 'None.'): string {
  if (!refs?.length) return fallback;
  return refs.map((ref) => referenceBlock('instruction-ref', { target: ref.target }, ref.instruction, '$instruction', ref.target)).join('\n\n');
}

export function referenceRoleList(refs: ReferenceRole[] | undefined, fallback = 'None.'): string {
  if (!refs?.length) return fallback;
  return refs.map((ref) => referenceBlock('role-ref', { target: ref.target }, ref.instruction, '$role', ref.target)).join('\n\n');
}

export function activityReportingGuidance(): string {
  return list(activityReportingRules);
}

export function toolsWithActivityReporting(tools: readonly string[] | undefined): string[] {
  return normalizeToolsForVsCode([...(tools ?? []), AGENT_FLOW_ACTIVITY_REPORT_TOOL]) ?? [AGENT_FLOW_ACTIVITY_REPORT_TOOL];
}

function referenceBlock(kind: string, attrs: Record<string, string>, instruction: string | undefined, placeholder: string, path: string): string {
  const attributes = Object.entries(attrs).map(([name, value]) => `${name}="${htmlAttribute(value)}"`).join(' ');
  const body = instruction ? instruction.replaceAll(placeholder, `\`${path}\``).trim() : '';
  return [`<!--agent-flow:begin ${kind} ${attributes}-->`, body, `<!--agent-flow:end ${kind}-->`].filter((part, index) => index !== 1 || part).join('\n');
}

function htmlAttribute(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}

function artifactActionLabel(action: string): string {
  const labels: Record<string, string> = {
    read: 'Read',
    write: 'Write',
    append: 'Append to',
    validate: 'Validate'
  };
  return labels[action] ?? action.charAt(0).toUpperCase() + action.slice(1);
}

export function frontmatterValue(value: string): string {
  return value.replace(/\n/g, ' ').replace(/"/g, '\\"');
}

export function yamlString(value: string): string {
  return `"${frontmatterValue(value)}"`;
}

export function yamlStringLine(name: string, value: string | string[] | undefined): string {
  if (Array.isArray(value)) return yamlList(name, value) + '\n';
  return value ? `${name}: ${yamlString(value)}\n` : '';
}

export function yamlBooleanLine(name: string, value: boolean | undefined): string {
  return typeof value === 'boolean' ? `${name}: ${value}\n` : '';
}

export function yamlList(name: string, items: string[] | undefined): string {
  if (!items || items.length === 0) return `${name}: []`;
  return `${name}:\n${items.map((item) => `  - ${yamlString(item)}`).join('\n')}`;
}

export function yamlOptionalList(name: string, items: string[] | undefined): string {
  return items && items.length > 0 ? `${yamlList(name, items)}\n` : '';
}

export function ensureTrailingNewline(content: string): string {
  return content.endsWith('\n') ? content : `${content}\n`;
}

export function appendGeneratedMarker(content: string): string {
  const clean = stripGeneratedMarker(content).trimEnd();
  return ensureTrailingNewline(clean ? `${clean}\n\n${GENERATED_MARKER}` : GENERATED_MARKER);
}

export function mergeMarkdownWithFrontmatter(markdown: string, frontmatter: string): string {
  const body = markdownBody(markdown);
  return appendGeneratedMarker(body.trim()
    ? `${frontmatter.trimEnd()}\n\n${body.trimStart()}`
    : `${frontmatter.trimEnd()}\n`);
}

export function replaceMarkdownSection(body: string, heading: string, content: string): string {
  const replacement = `# ${heading}\n\n${content.trimEnd() || 'None.'}`;
  const match = new RegExp(`^# ${escapeRegExp(heading)}\\s*$`, 'm').exec(body);
  if (!match) return [body.trimEnd(), replacement].filter(Boolean).join('\n\n');

  const afterHeading = match.index + match[0].length;
  const nextHeading = /^# .+$/m.exec(body.slice(afterHeading));
  const end = nextHeading ? afterHeading + nextHeading.index : body.length;
  const before = body.slice(0, match.index).trimEnd();
  const after = body.slice(end).trimStart();
  return [before, replacement, after].filter(Boolean).join('\n\n');
}

export function markdownBody(markdown: string): string {
  const content = stripGeneratedMarker(markdown).trimStart();
  if (!content.startsWith('---')) return content;
  const end = content.indexOf('\n---', 3);
  if (end < 0) return content;
  return content.slice(end + 4).replace(/^(?:\r?\n)+/, '');
}

function stripGeneratedMarker(markdown: string): string {
  let content = markdown.trimStart();
  for (const marker of [GENERATED_MARKER, LEGACY_GENERATED_MARKER]) {
    if (content.startsWith(marker)) content = content.slice(marker.length).replace(/^(?:\r?\n)+/, '');
  }
  for (const marker of [GENERATED_MARKER, LEGACY_GENERATED_MARKER]) {
    if (content.trimEnd().endsWith(marker)) {
      content = content.trimEnd().slice(0, -marker.length).replace(/(?:\r?\n)+$/, '');
    }
  }
  return content;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export function nodeFileStem(id: string, label: string, type: string): string {
  return id.startsWith(`new-${type}-`) ? slugifyFileStem(label, id) : id;
}

function slugifyFileStem(value: string, fallback: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || fallback;
}
